[project]
name = "demo-graph"
version = "0.1.0"
description = "Demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.0",
    "gspread>=6.2.1",
    "kaig",
    "pyyaml>=6.0.2"
]

[project.scripts]
cli = "demo_graph.main:cli"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
kaig = { workspace = true }

[tool.basedpyright]
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportAny = false
reportUnknownArgumentType = false
reportExplicitAny = false
reportUnknownLambdaType = false
